### ISSUE TITLE
"You are seeing this message because ad or script blocking software is interfering with this page." showing for customer with "no advertising" purchased

### ISSUE THREAD

**Issue by hanecak** [remp2020/remp#147]
I am a paying customer of DennikN.sk and I have a subscription which includes among other things "no advertisement". But I see following message at the bottom of their website, even when logged in:

"You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page."

Since I'm not supposed to see any advertising, I see no point in being reminded that I'm using ad-blocker and I see no need to add any exceptions or to disable it. But, given "no advertising" option being purchased, I believe I can reasonably expect it is responsibility of the website in question (i.e. DennikN) to make sure such notification is NOT displayed to me.

Response from DennikN indicates, that this component is responsible for that message.

And since they also indicated they are not able to fix that themselves, I'm raising this issue here myself.

Side note: Same issue and I suspect same code (i.e. this REMP) is present also on sme.sk .

**Comment by rootpd** [comment]
Hi, unfortunately this is not done by REMP, even though one of our tools supports displaying the message for adblock users. The message on dennikn.sk and sme.sk is displayed by a Google-based technology which is integrated into the web.

That integration should also make sure, that it's initialized only for a set of users it's supposed to target - and possibly exclude paying subscribers. Even if both websites used REMP's tool to display the message, it's again something that needs to be configured and integrated. Tool itself has no knowledge of subscriptions, or who to display the message to; it's by design.
