### ISSUE TITLE
Email as default login function

### ISSUE THREAD

**Issue by mechiles** [remp2020/remp#216]
This may not be an issue, per se, but instead of relying on Google email login, by default, is there a way to enable login via email address and password using the Laravel SSO authentication? I want to set it up in a manner of different options to login where the user may not have a Gmail account.

**Comment by rootpd** [comment]
Hi, there are ways but they don't work out of the box. We have installations that required extendability of SSO (exactly because they wanted to use their own system and not Google login), so we added the option to extend the SSO.

See https://github.com/remp2020/remp/tree/master/Sso#custom-providers

The idea here is that you'll implement your own controller doing the authentication - "how" it authenticates the user is completely up to you. Once the user is authenticated, SSO stores the user data and the rest of authentication in the other apps are done against this authenticated instance.

Unfortunately, at the moment this is only achievable if you fork the SSO. We already have extendability of our Laravel apps (Sso, Beam, Campaign) in the plan, so hopefully that should be available during this year and no forking will be necessary.

**Comment by mechiles** [comment]
Thanks, @rootpd. I'll see what I can do and be on the lookout for the updates.
